server:
  port: 8081
spring:
  profiles: local
  application:
    name: rental-car-reservation-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
secrets:
  path:
    dataSourceDriverClassName: C:\Users\OSokhan\Documents\secrets\sagapattern\rental-car\dataSourceDriverClassName
    dataSourceUrl: C:\Users\OSokhan\Documents\secrets\sagapattern\rental-car\dataSourceUrl
    dataSourceUsername: C:\Users\OSokhan\Documents\secrets\sagapattern\rental-car\dataSourceUsername
    dataSourcePassword: C:\Users\OSokhan\Documents\secrets\sagapattern\rental-car\dataSourcePassword
